
export const STATUSES: string[] = [
    "Already Rehomed",
    "Asked for more info",
    "Bad # or No VM",
    "Duplicate",
    "Found Pet",
    "Keeping-Behavior",
    "Keeping- Medical",
    "Keeping- Other",
    "Kitten Pack & S/N",
    "LM with Info",
    "Lost Pet",
    "No Show Appt",
    "Not PSN",
    "Open",
    "Owner Surrender Intake",
    "PSN Boarding",
    "Rehome Attempt",
    "Rehome Confirmed",
    "Reunited",
    "Surrender Appt",
    "Surrender Denied",
    "Walk-in Surrender Attempt",
    "Walk-in- Stray Attempt",
    "Walk-In- OS Intake",
    "Walk-in- Stray Intake",
    "Walk-in- Other",
    "Call elevated to management",
    "ACPS",
    "Counseling in Progress",
    "Intake",
    "HSH",
    "Referred to External Service",
    "Appointment Made"
  ];

  export const SPECIES: string[] = [
    "Adult Dog",
    "Adult Cat",
    "Puppy",
    "Kitten",
    "Large Dog",
    "Small Dog"
  ]